apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-app-frontend
  name: my-app-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: my-app-frontend
  type: LoadBalancer  