apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: my-app-frontend
  name: my-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: my-app-frontend
  template:
    metadata:
      labels:
        service: my-app-frontend
        api: external        
    spec:
      containers:
      - image: wonderkin/udagram-frontend:latest
        name: my-app-frontend
        imagePullPolicy: Always        
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always