apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-app-reverseproxy
  name: my-app-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: my-app-reverseproxy
  type: LoadBalancer    